steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops-dev:$SHORT_SHA", "."]

  # Push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops-dev:$SHORT_SHA"]

  # Authenticate with GKE cluster
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "container"
      - "clusters"
      - "get-credentials"
      - "gcp-devops-project"
      - "--zone"
      - "us-central1-c"
      - "--project"
      - "$PROJECT_ID"

  # Apply Kubernetes manifests
  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=gcp-devops-project"
    args: ["apply", "-f", "gke.yaml", "-n", "gcp-devops-dev"]

  # Wait for Deployment rollout
  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=gcp-devops-project"
    args: ["rollout", "status", "deployment/gcp-devops-gke-dev", "-n", "gcp-devops-dev"]

options:
  logging: CLOUD_LOGGING_ONLY
