steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops:latest", "."]

  # Push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops:latest"]

  # Authenticate kubectl to the cluster
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials gcp-devops-project --zone us-central1-c
        echo "Cluster authentication successful"

  # Set the image in the Kubernetes Deployment
  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=gcp-devops-project"
    args: ["set", "image", "deployment/gcp-devops-gke", "gcp-devops-gke=gcr.io/$PROJECT_ID/gcpdevops:latest", "-n", "gcp-devops-prod"]

  # Apply the updated deployment and service
  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=gcp-devops-project"
    args: ["apply", "-f", "gke.yaml", "-n", "gcp-devops-prod"]  # Correct file path

options:
  logging: CLOUD_LOGGING_ONLY

