steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops-dev:$SHORT_SHA", "."]

  # Push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops-dev:$SHORT_SHA"]

  # Deploy the container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/$PROJECT_ID/gcpdevops-dev:$SHORT_SHA
      - --location=us-central1-c
      - --cluster=gcp-devops-project
      - --namespace=gcp-devops-dev

options:
  logging: CLOUD_LOGGING_ONLY

## testing  