apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke-dev
  namespace: gcp-devops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke-dev
        image: gcr.io/global-ace-450915-r9/gcpdevops-dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5


apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service-dev
  namespace: gcp-devops-dev
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: gcp
  type: LoadBalancer